MODEL:
  TYPE: swin
  NAME: swin_tiny_patch4_window7_224
  DROP_PATH_RATE: 0.0
  PRETRAIN_CKPT: "./pretrained_ckpt/swin_tiny_patch4_window7_224.pth"
  SWIN:
    FINAL_UPSAMPLE: "expand_first"
    EMBED_DIM: 128
    DEPTHS: [ 2, 2, 18, 2 ]
    DECODER_DEPTHS: [ 2, 18, 2, 1 ]
    NUM_HEADS: [ 4, 8, 16, 32 ]
    WINDOW_SIZE: 7
